on:
  push:
    branches:
      - 'main'

jobs:
  get_changed_posts:
    runs-on: ubuntu-latest
    outputs:
      posts: ${{ steps.getPosts.outputs.posts }}

    steps:
      - id: checkout
        name: Check out repository
        uses: actions/checkout@v2
      - id: getPosts

  add_and_update_datetimes:
    runs-on: ubuntu-latest
    needs: get_changed_posts

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

  create_discussion:
    runs-on: ubuntu-latest
    needs: add_and_update_datetimes
